# Generated by Django 5.2 on 2025-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='ticket_id',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
    ]
